import { Container } from "@/components/Container";
import { Header } from "@/components/navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const calSansFont = localFont({
  src: "../../fonts/CalSans-SemiBold.woff2",
  variable: "--font-calsans",
});

export const metadata: Metadata = {
  title: "PeerSci",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          <div>{children}</div>
        </Container>
      </body>
    </html>
  );
}
